frontend/controllers/PagesController.php
<?php

namespace frontend\controllers;

class PagesController extends \yii\web\Controller
{

    // public $layout = 'column-2';

    public function actionAboutBudget()
    {
        return $this->render('about-budget');
    }

    public function actionIncome() {
        return $this->render('income');
    }

    public function actionBudgetProcess() {
        return $this->render('budget-process');
    }

    public function actionBudgetSystem() {
        return $this->render('budget-system');
    }

    public function actionInterbudget() {
        return $this->render('interbudget');
    }

    public function actionGlossary() {
        return $this->render('glossary_' . \Yii::$app->language);
    }



}

frontend/views/pages/_budget_menu.php
<?php
    use yii\helpers\Html;
?>
<ul class="subheading_menu">
  <li class="<?=(Yii::$app->controller->action->id == 'about-budget')?'active':''?>">
      <?=Html::a(Yii::t("app", "Бюджет"), ["/pages/about-budget"])?></li>
  <li class="<?=(Yii::$app->controller->action->id == 'income')?'active':''?>" >
       <?=Html::a(Yii::t("app", "Доходы"), ["/pages/income"])?></li>
  <li class="<?=(Yii::$app->controller->action->id == 'budget-process')?'active':''?>">
      <?=Html::a(Yii::t("app", "Бюджетный процесс"), ["/pages/budget-process"])?></li>
  <li class="<?=(Yii::$app->controller->action->id == 'budget-system')?'active':''?>">
      <?=Html::a(Yii::t("app", "Принципы бюджетной системы"), ["/pages/budget-system"])?></li>
</ul>

frontend/views/pages/about-budget.php
<?php

    $this->title = Yii::t('app', 'О Бюджете');
    // $this->params['breadcrumbs'][] = $this->title;
?>


<div class="page about-budget">


    <div class="heading"><?=$this->title?></div>

    <?=$this->render('_budget_menu')?>

    <div class="block-1">

        <div class="row">
            <div class="col-sm-12">
                <p><?=Yii::t('app', '<b>Бюджет</b> - централизованный денежный фонд государства, предназначенный для финансового обеспечения реализации его задач и функций (ст.3 БК РК)')?></p>
                <p><?=Yii::t('app', 'Бюджет составляется уполномоченным органом по государственному планированию и утверждается решениями соответствующих маслихатов . По окончании финансового года ответственный уполномоченный орган по исполнению бюджета должно отчитаться об исполнении бюджета.')?></p>
            </div>
            <div class="col-sm-12">
                <div class="center" style="padding-top: 30px;"><img class="img img-responsive" src="/images/image-1.png" /></div>
            </div>
        </div>

        <p><?=Yii::t('app', 'Государственный бюджет состоит из ДОХОДНОЙ ЧАСТИ и РАСХОДНОЙ ЧАСТИ')?></p>
        <ul>
            <li><?=Yii::t('app', 'ДОХОДНАЯ ЧАСТЬ показывает источники денежных средств бюджета')?></li>
            <li><?=Yii::t('app', 'РАСХОДНАЯ ЧАСТЬ показывает на какие цели направляются аккумулированные государством средства')?></li>
        </ul>
        <p><?=Yii::t('app', 'Если расходная часть бюджета превышает доходную, то бюджет сводится с дефицитом. Превышение доходов над расходами образует положительный остаток бюджета - профицит.')?></p>
        <p><?=Yii::t('app', 'Дефицит (профицит) бюджета равен разнице между доходами и затратами, чистым бюджетным кредитованием и сальдо по операциям с финансовыми активами. Полученная величина с отрицательным знаком является дефицитом, с положительным знаком - профицитом бюджета (ст.17 БК РК)')?></p>
        <p><?=Yii::t('app', 'СБАЛАНСИРОВАННОСТЬ БЮДЖЕТА ПО ДОХОДАМ И РАСХОДАМ — ОСНОВОПОЛАГАЮЩЕЕ ТРЕБОВАНИЕ, ПРЕДЪЯВЛЯЕМОЕ К ОРГАНАМ, СОСТАВЛЯЮЩИМ И УТВЕРЖДАЮЩИМ БЮДЖЕТ.')?></p>

    </div>

</div>

frontend/views/pages/budget-process.php
<?php

    $this->title = Yii::t('app', 'Бюджетный процесс');
    // $this->params['breadcrumbs'][] = $this->title;
?>


<div class="page about-budget">


    <div class="heading"><?=$this->title?></div>
    <?=$this->render('_budget_menu')?>

    <div class="block-3">
        <p style="padding-bottom: 30px;">
            <?=Yii::t('app', '<b>Бюджетный процесс</b> – регламентированная бюджетным законодательством Республики Казахстан деятельность государственных органов по планированию, рассмотрению, утверждению, исполнению, уточнению и корректировке бюджета, ведению бухгалтерского учета и финансовой отчетности, бюджетного учета и бюджетной отчетности, государственному аудиту и финансовому контролю, бюджетному мониторингу и оценке результатов.')?>
        </p>

        <img class="img img-responsive" src="/images/image-2.png" />

        <ul class="nav nav-tabs">
          <li class="active tab1"><a data-toggle="tab" href="#menu1"><?=Yii::t("app", "Этап 1: Составление");?></a></li>
          <li class="tab2" ><a data-toggle="tab" href="#menu2"><?=Yii::t("app", "Этап 2: Утверждение");?></a></li>
          <li class="tab3"><a data-toggle="tab" href="#menu3"><?=Yii::t("app", "Этап 3: Исполнение");?></a></li>
          <li class="tab4"><a data-toggle="tab" href="#menu4"><?=Yii::t("app", "Этап 4: Отчетность");?></a></li>
          <li class="tab5"><a data-toggle="tab" href="#menu5"><?=Yii::t("app", "Этап 5: Контроль");?></a></li>
        </ul>

        <div class="tab-content">
            <div id="menu1" class="tab-pane fade in active">
                <p class="sub">
                    <p><?=Yii::t('app', 'Областной бюджет, бюджеты города республиканского значения, столицы, районный (города областного значения) бюджет ежегодно разрабатываются на плановый период местными уполномоченными органами по государственному планированию с учетом прогноза социально-экономического развития области, городов республиканского значения, столицы. ')?></p>
                    <p><?=Yii::t('app', 'Бюджеты города районного значения, села, поселка, сельского округа ежегодно разрабатываются на плановый период аппаратами акимов города районного значения, села, поселка, сельского округа с учетом прогноза социально-экономического развития области.')?></p>
                    <p><?=Yii::t('app', 'Проект бюджета составляются и утверждаются сроком на три года - очередной финансовый год и плановый период.')?></p>

                </p>
            </div>
            <div id="menu2" class="tab-pane fade">
                <p class="sub">
                    <p><?=Yii::t('app', 'Местный уполномоченный орган по государственному планированию составляет проект бюджета и вносит его на рассмотрение бюджетной комиссии. После рассмотрения и определения, проект вносится местным исполнительным органом в соответствующий маслихат на утверждение.')?></p>
                    <p><?=Yii::t('app', 'Областной бюджет утверждается маслихатом не позднее двухнедельного срока после подписания Президентом Республики Казахстан закона о республиканском бюджете. Районный (города областного значения) бюджет утверждается не позднее двухнедельного срока после подписания решения областного маслихата об утверждении областного бюджета.')?></p>
                    <p><?=Yii::t('app', 'Областной бюджет утверждается маслихатом не позднее двухнедельного срока после подписания Президентом Республики Казахстан закона о республиканском бюджете. Районный (города областного значения) бюджет утверждается не позднее двухнедельного срока после подписания решения областного маслихата об утверждении областного бюджета.')?></p>
                </p>
            </div>
            <div id="menu3" class="tab-pane fade">
                <p class="sub">
                    <p><?=Yii::t('app', 'Исполнение бюджета осуществляется в пределах объемов бюджетных средств на соответствующий финансовый год, утвержденных законом о республиканском бюджете или решением маслихата о местном бюджете, начинается 1 января и завершается 31 декабря текущего финансового года.')?></p>
                    <p><?=Yii::t('app', 'Исполнением бюджета является выполнение комплекса мероприятий по обеспечению поступлений в бюджет, реализации бюджетных программ (подпрограмм), финансированию дефицита (использованию профицита) бюджета.')?></p>
                    <p><?=Yii::t('app', 'Кассовое обслуживание исполнения бюджетов бюджетной системы региона осуществляется территориальным подразделением казначейства. ')?></p>
                    <p><?=Yii::t('app', 'Исполнение бюджета обеспечивается полнотой и своевременностью уплаты в бюджет всех видов бюджетных поступлений, зачислением их на Единый казначейский счет (далее - ЕКС) и своевременным осуществлением платежей и переводов с ЕКС в целях реализации мероприятий, направленных на достижение целей бюджетных программ.')?></p>
                    <p><?=Yii::t('app', 'Организация исполнения бюджета и координация деятельности администраторов бюджетных программ по исполнению бюджета возлагается на соответствующий уполномоченный орган по исполнению бюджета.')?></p>
                </p>
            </div>
            <div id="menu4" class="tab-pane fade">
                <p class="sub">
                    <p><?=Yii::t('app', 'Бюджетный учет представляет собой упорядоченную систему сбора, регистрации и обобщения информации в денежном выражении об операциях с единого казначейского счета и счетов государственных учреждений, о требованиях и обязательствах местных исполнительных органов.')?></p>
                </p>
            </div>
            <div id="menu5" class="tab-pane fade">
                <p class="sub">
                    <p><?=Yii::t('app', 'На стадии контроля в текущем году осуществляется государственный финансовый контроль за соблюдением бюджетного законодательства при использовании бюджетных средств, а также за соблюдением внутренних стандартов и процедур составления и исполнения бюджета, составления бюджетной отчетности и ведения бюджетного учета, а также подготовку и организацию осуществления мер, направленных на повышение результативности (эффективности и экономности) использования бюджетных средств.')?></p>
                </p>
            </div>
        </div>
    </div>

</div>

frontend/views/pages/budget-system.php
<?php

    $this->title = Yii::t('app', 'Принципы бюджетной системы');
?>

<div class="page budget-systems">


    <div class="heading"><?=$this->title?></div>
    <?=$this->render('_budget_menu')?>

    <div class="block-1">

        <div class="principe-info" data-show="#principe-1">
            <img class="img img-responsive" src="/images/style/process-1.png" />
            <div class="text"><?=Yii::t('app', 'Единство бюджетной системы')?></div>
            <div class="number">1</div>
        </div>
        <div class="principe-info" data-show="#principe-2">
            <img class="img img-responsive" src="/images/style/process-2.png" />
            <div class="text"><?=Yii::t('app', 'Полнота отражений показателей бюджетов')?></div>
            <div class="number">2</div>
        </div>
        <div class="principe-info" data-show="#principe-3">
            <img class="img img-responsive" src="/images/style/process-3.png" />
            <div class="text"><?=Yii::t('app', 'Достоверность бюджета')?></div>
            <div class="number">3</div>
        </div>
        <div class="principe-info" data-show="#principe-4">
            <img class="img img-responsive" src="/images/style/process-4.png" />
            <div class="text"><?=Yii::t('app', 'Адресность и целевой характер бюджетных средств')?></div>
            <div class="number">4</div>
        </div>
        <div class="principe-info" data-show="#principe-5">
            <img class="img img-responsive" src="/images/style/process-5.png" />
            <div class="text"><?=Yii::t('app', 'Разграничение доходов, расходов и источников финансирования')?></div>
            <div class="number">5</div>
        </div>
        <div class="principe-info" data-show="#principe-6">
            <img class="img img-responsive" src="/images/style/process-6.png" />
            <div class="text"><?=Yii::t('app', 'Результативная разработка и исполнение бюджета')?></div>
            <div class="number">6</div>
        </div>
        <div class="principe-info" data-show="#principe-7">
            <img class="img img-responsive" src="/images/style/process-7.png" />
            <div class="text"><?=Yii::t('app', 'Самостоятельность бюджетов')?></div>
            <div class="number">7</div>
        </div>
        <div class="principe-info" data-show="#principe-8">
            <img class="img img-responsive" src="/images/style/process-8.png" />
            <div class="text"><?=Yii::t('app', 'Подведомственность расходов бюджетов')?></div>
            <div class="number">8</div>
        </div>
        <div class="principe-info" data-show="#principe-9">
            <img class="img img-responsive" src="/images/style/process-9.png" />
            <div class="text"><?=Yii::t('app', 'Сбалансированность бюджета')?></div>
            <div class="number">9</div>
        </div>
        <div class="principe-info" data-show="#principe-10">
            <img class="img img-responsive" src="/images/style/process-10.png" />
            <div class="text"><?=Yii::t('app', 'Равенство бюджетных прав')?></div>
            <div class="number">10</div>
        </div>
        <div class="principe-info" data-show="#principe-11">
            <img class="img img-responsive" src="/images/style/process-11.png" />
            <div class="text"><?=Yii::t('app', 'Единство кассы')?></div>
            <div class="number">11</div>
        </div>
        <div class="principe-info" data-show="#principe-12">
            <img class="img img-responsive" src="/images/style/process-12.png" />
            <div class="text"><?=Yii::t('app', 'Результативность и эффективность бюджетных средств')?></div>
            <div class="number">12</div>
        </div>
        <div class="principe-info" data-show="#principe-13">
            <img class="img img-responsive" src="/images/style/process-13.png" />
            <div class="text"><?=Yii::t('app', 'Общее покрытие расходов бюджета')?></div>
            <div class="number">13</div>
        </div>
        <div class="principe-info" data-show="#principe-14">
            <img class="img img-responsive" src="/images/style/process-14.png" />
            <div class="text"><?=Yii::t('app', 'Адресность и целевой характер бюджетных средств')?></div>
            <div class="number">14</div>
        </div>
    </div>



<?php
    yii\bootstrap\Modal::begin([
        'header' => "<b>$this->title</b>",
        'id' => 'principe-modal',
        'size' => 'modal-lg'
    ]);
?>

<div class="principes">

    <div id="principe-1">
        <div class="row">
            <div class="col-xs-2"><img src="/images/style/process-1-1k.png" /></div>
            <div class="col-xs-10">
                <?=Yii::t('app', 'Принцип единства означает применение единых принципов организации и функционирования бюджетной системы, использование единой бюджетной классификации, единых процедур и технических решений бюджетного процесса в Республике Казахстан')?>
            </div>
        </div>
    </div>
    <div id="principe-2">
        <div class="row">
            <div class="col-xs-2"><img src="/images/style/process-2-2k.png" /></div>
            <div class="col-xs-10">
                <?=Yii::t('app', 'Принцип полноты отражение в бюджете и Национальном фонде Республики Казахстан всех поступлений и расходов, предусмотренных законодательством Республики Казахстан, недопущение зачетов взаимных требований с использованием бюджетных средств, равно как и уступок прав требований по бюджетным средствам')?>
            </div>
        </div>
    </div>
    <div id="principe-3">
        <div class="row">
            <div class="col-xs-2"><img src="/images/style/process-3-3k.png" /></div>
            <div class="col-xs-10">
                <?=Yii::t('app', 'Принцип реалистичности соответствие утвержденных (уточненных, скорректированных) показателей бюджета утвержденным (уточненным, скорректированным) параметрам, направлениям прогнозов социально-экономического развития, стратегических планов государственных органов, программ развития территорий')?>
            </div>
        </div>
    </div>
    <div id="principe-4">
        <div class="row">
            <div class="col-xs-2"><img src="/images/style/process-4-4k.png" /></div>
            <div class="col-xs-10">
                <?=Yii::t('app', 'Принцип транспарентности обязательное опубликование нормативных правовых актов в области бюджетного законодательства Республики Казахстан, утвержденных (уточненных, скорректированных) бюджетов и отчетов об их исполнении, гражданского бюджета, стратегических планов и отчетов об их реализации, о формировании и об использовании Национального фонда Республики Казахстан, за исключением сведений, составляющих государственную или иную охраняемую законом тайну, а также обязательная открытость бюджетного процесса для общества и средств массовой информации')?>
            </div>
        </div>
    </div>
    <div id="principe-5">
        <div class="row">
            <div class="col-xs-2"><img src="/images/style/process-5-5k.png" /></div>
            <div class="col-xs-10">
                <?=Yii::t('app', 'Принцип последовательности  соблюдение государственными органами ранее принятых решений в сфере бюджетных отношений')?>
            </div>
        </div>
    </div>
    <div id="principe-6">
        <div class="row">
            <div class="col-xs-2"><img src="/images/style/process-6-6k.png" /></div>
            <div class="col-xs-10">
                <?=Yii::t('app', 'Принцип результативности разработка и исполнение бюджета, ориентированного на достижение показателей результатов, предусмотренных стратегическими планами, программами развития территорий и (или) бюджетными программами государственных органов')?>
            </div>
        </div>
    </div>
    <div id="principe-7">
        <div class="row">
            <div class="col-xs-2"><img src="/images/style/process-7-7k.png" /></div>
            <div class="col-xs-10">
                <?=Yii::t('app', 'Принцип самостоятельности бюджета установление стабильного распределения поступлений между бюджетами разных уровней и определение направлений их расходования в соответствии с настоящим Кодексом, право всех уровней государственного управления самостоятельно осуществлять бюджетный процесс в соответствии с настоящим Кодексом, недопустимость изъятия доходов, дополнительно полученных в ходе исполнения местных бюджетов, и остатков бюджетных средств местных бюджетов в вышестоящие бюджеты, недопустимость возложения на нижестоящие бюджеты дополнительных расходов без соответствующей их компенсации')?>
            </div>
        </div>
    </div>
    <div id="principe-8">
        <div class="row">
            <div class="col-xs-2"><img src="/images/style/process-8-8k.png" /></div>
            <div class="col-xs-10">
                <?=Yii::t('app', 'Принцип преемственности планирование республиканского и местных бюджетов, основанное на прогнозах социально-экономического развития, базовых расходах, утвержденных в предыдущие периоды, итогах бюджетного мониторинга, оценке результатов')?>
            </div>
        </div>
    </div>
    <div id="principe-9">
        <div class="row">
            <div class="col-xs-2"><img src="/images/style/process-9-9k.png" /></div>
            <div class="col-xs-10">
                <?=Yii::t('app', 'Принцип обоснованности планирование бюджета на основе нормативных правовых актов и других документов, определяющих необходимость включения в проект бюджета тех или иных поступлений или расходов и обоснованность их объемов, а также использование бюджетных средств и активов государства в соответствии с законодательством Республики Казахстан')?>
            </div>
        </div>
    </div>
    <div id="principe-10">
        <div class="row">
            <div class="col-xs-2"><img src="/images/style/process-10-10k.png" /></div>
            <div class="col-xs-10">
                <?=Yii::t('app', 'Принцип своевременности зачисление поступлений в республиканский и местные бюджеты, на контрольный счет наличности Национального фонда Республики Казахстан и перевод их на счета Правительства в Национальном Банке Республики Казахстан, принятие обязательств государственными учреждениями в соответствии с индивидуальными планами финансирования по обязательствам, проведение платежей в соответствии с индивидуальными планами финансирования по платежам и перечисление бюджетных средств на счета получателей бюджетных средств в сроки с соблюдением порядка, установленного соответствующими нормативными правовыми актами')?>
            </div>
        </div>
    </div>
    <div id="principe-11">
        <div class="row">
            <div class="col-xs-2"><img src="/images/style/process-11-11k.png" /></div>
            <div class="col-xs-10">
                <?=Yii::t('app', 'Принцип единства кассы зачисление всех поступлений в бюджет на единый казначейский счет и осуществление всех предусмотренных расходов с единого казначейского счета в национальной валюте')?>
            </div>
        </div>
    </div>
    <div id="principe-12">
        <div class="row">
            <div class="col-xs-2"><img src="/images/style/process-12-12k.png" /></div>
            <div class="col-xs-10">
                <?=Yii::t('app', 'Принцип эффективности разработка и исполнение бюджета исходя из необходимости достижения наилучшего прямого и конечного результата с использованием утвержденного объема бюджетных средств или достижения прямого и конечного результата с использованием меньшего объема бюджетных средств')?>
            </div>
        </div>
    </div>
    <div id="principe-13">
        <div class="row">
            <div class="col-xs-2"><img src="/images/style/process-13-13.png" /></div>
            <div class="col-xs-10">
                <?=Yii::t('app', 'Принцип ответственности принятие необходимых административных и управленческих решений, направленных на достижение прямых и конечных результатов и обеспечение ответственности администраторов бюджетных программ и руководителей государственных учреждений и субъектов квазигосударственного сектора за принятие решений, не соответствующих законодательству Республики Казахстан')?>
            </div>
        </div>
    </div>
    <div id="principe-14">
        <div class="row">
            <div class="col-xs-2"><img src="/images/style/process-14-14k.png" /></div>
            <div class="col-xs-10">
                <?=Yii::t('app', 'Принцип адресности и целевого характера бюджетных средств направление и использование бюджетных средств администраторами бюджетных программ, субъектами квазигосударственного сектора для достижения показателей результатов, предусмотренных стратегическими планами, программами развития территорий и (или) бюджетными программами государственных органов, финансово-экономическими обоснованиями бюджетных инвестиций, посредством участия в уставном капитале субъектов квазигосударственного сектора с соблюдением законодательства Республики Казахстан')?>
            </div>
        </div>
    </div>
</div>


<?php
    yii\bootstrap\Modal::end();
?>

</div>

frontend/views/pages/income.php
<?php

    $this->title = Yii::t('app', 'Доходы');
    // $this->params['breadcrumbs'][] = $this->title;
?>


<div class="page about-budget">


    <div class="heading"><?=$this->title?></div>
    <?=$this->render('_budget_menu')?>

    <div class="block-2">
        <div class="center"><img class="image image-responsive" src="/images/money-2.png" /></div>
        <h4 class="center"></h4>
        <p class="center subhead"><?=Yii::t('app', 'Безвозмездные и безвозвратные<br />поступления денежных средств в бюджет')?></p>
        <br />
        <br />
        <div class="row">
            <div class="col-sm-4">
                <div class="schema-container">
                    <div class="schema">
                        <div class="image-container type1"><img class="img img-responsive" src="/images/money-1.png" /></div>
                        <center><img width="180px" src="/images/style/tree-1.png" /></center>
                        <p class="i-heading"><?=Yii::t('app', 'НАЛОГОВЫЕ ПОСТУПЛЕНИЯ')?></p>
                        <p class="i-content"><?=Yii::t('app', 'Поступление уплаты от физических и юридических лиц установленных Законодательством РК')?></p>
                    </div>

                    <center><img width="60px" style="padding-bottom: 40px;" src="/images/style/Document_icon.png" /></center>
                    <p class="example-header"><span><?=Yii::t('app', 'ПРИМЕРЫ')?></span></p>
                    <ul class="styled green">
                        <li><?=Yii::t('app', 'Индивидуальный подоходный налог')?></li>
                        <li><?=Yii::t('app', 'Социальный налог')?></li>
                        <li><?=Yii::t('app', 'Налоги на собственность')?></li>
                        <li><?=Yii::t('app', 'Земельный налог')?></li>
                        <li><?=Yii::t('app', 'Транспортный налог')?></li>
                        <li><?=Yii::t('app', 'Прочие налоги')?></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="schema-container">
                    <div class="schema">
                        <div class="image-container type1"><img class="img img-responsive" src="/images/money-1.png" /></div>
                        <center><img width="180px" src="/images/style/tree-2.png" /></center>
                        <p class="i-heading"><?=Yii::t('app', 'НЕНАЛОГОВЫЕ ПОСТУПЛЕНИЯ')?></p>
                        <p class="i-content"><?=Yii::t('app', 'Поступление уплаты от физических, юридических лиц и других платежей установленных Законодательством РК')?></p>
                    </div>

                    <center><img width="60px" style="padding-bottom: 40px;" src="/images/style/Document_icon.png" /></center>
                    <p class="example-header"><span><?=Yii::t('app', 'ПРИМЕРЫ')?></span></p>
                    <ul class="styled green">
                        <li><?=Yii::t('app', 'Доходы от использования имущества, назодящегося в гос. собственности')?></li>
                        <li><?=Yii::t('app', 'Отчисления недропользователей на социально - экономическое развитие региона и инфраструктуры')?></li>
                        <li><?=Yii::t('app', 'Прочие неналоговые поступления')?></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="schema-container">
                    <div class="schema">
                        <div class="image-container type1"><img class="img img-responsive" src="/images/money-1.png" /></div>
                        <center><img width="180px" src="/images/style/tree-3.png" /></center>
                        <p class="i-heading"><?=Yii::t('app', 'ПОСТУПЛЕНИЯ ОТ ПРОДАЖИ ОСНОВНОГО КАПИТАЛА')?></p>
                    </div>

                    <center><img width="60px" style="padding-bottom: 40px;" src="/images/style/Document_icon.png" /></center>
                    <p class="example-header"><span><?=Yii::t('app', 'ПРИМЕРЫ')?></span></p>
                    <ul class="styled green">
                        <li><?=Yii::t('app', 'Продажа государственного имущества закрепленного за государственными учреждениями')?></li>
                        <li><?=Yii::t('app', 'Продажа земли и нематериальных активов')?></li>
                        <li><?=Yii::t('app', 'Поступления от продажи квартир гражданам')?></li>
                    </ul>
                </div>
            </div>
            <!-- <div class="col-sm-3">
                <div class="schema-container">
                    <div class="schema">
                        <div class="image-container type1"><img class="img img-responsive" src="/images/money-1.png" /></div>
                        <p class="i-heading"><?=Yii::t('app', 'ПОСТУПЛЕНИЯ ТРАНСФЕРТОВ')?></p>
                    </div>

                    <p class="example-header"><span><?=Yii::t('app', 'ПРИМЕРЫ')?></span></p>
                    <ul class="styled green">
                        <li><?=Yii::t('app', 'Трансферты из вышестоящих органов государственного управления')?></li>
                    </ul>
                </div>
            </div> -->
        </div>

    </div>

</div>

frontend/views/pages/index.php
<?php
/* @var $this yii\web\View */
?>
<h1>pages/index</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>