common/models/Reports.php
<?php

namespace common\models;

use Yii;
use common\models\helpers\ExcellImport;
/**
 * This is the model class for table "reports".
 *
 * @property int $id
 * @property string $date
 * @property int $type_id
 * @property int $city_id
 * @property string $filename
 * @property string $data
 */
class Reports extends \yii\db\ActiveRecord
{



    public $file;


    public static function tableName()
    {
        return 'reports';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date', 'date_fact', 'type_id', 'city_id', 'filename'], 'required'],
            [['date'], 'safe'],
            [['status'], 'boolean'],
            [['type_id', 'city_id'], 'integer'],
            [['data'], 'string'],
            [['filename'], 'string', 'max' => 128],
            [['file'], 'file', 'skipOnEmpty' => false, 'extensions' => ['xls', 'xlsx'], 'on' => 'create'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'date' => Yii::t('app', 'Дата'),
            'type_id' => Yii::t('app', 'Тип'),
            'city_id' => Yii::t('app', 'Город'),
            'filename' => Yii::t('app', 'Файл'),
            'data' => Yii::t('app', 'Информация'),
            'type.name' => Yii::t('app', 'Тип'),
            'city.name' => Yii::t('app', 'Город'),
        ];
    }

    public function getType() {
        return $this->hasOne(ReportTypes::className(), ['id'=>'type_id']);
    }

    public function getCity() {
        return $this->hasOne(Cities::className(), ['id'=>'city_id']);
    }

    public function getItems() {
        return $this->hasMany(ReportItems::className(), ['report_id' => 'id']);
    }

    public function getIncomes() {
        return ReportItems::find()->innerJoin('report_item_categories cat', 'cat.id = report_items.category_id')
            ->where(['=', 'report_id', $this->id])->andWhere(['=', 'cat.fullname', 'ДОХОДЫ'])->one();
    }

    public function getOutcomes() {
        return ReportItems::find()->innerJoin('report_item_categories cat', 'cat.id = report_items.category_id')
            ->where(['=', 'report_id', $this->id])->andWhere(['=', 'cat.fullname', 'ЗАТРАТЫ'])->one();
    }


    public function getTree() {
        // $models = self::find()->innerJoin('report_item_categories cats', ['report_items.category_id = cats.id'])
        //     ->innerJoin('report_item_categories subcats', ['subcats.parent_id = cats.id'])
        //     ->where('report_items.report_id = ')

        return self::nodetree();

    }

    public function shortTree() {
        if($this->data) return json_decode($this->data, true);
        $refs = array();
        $list = array();

        $nodes = Yii::$app->db->createCommand('select * from report_item_categories')->queryAll();

        foreach ($nodes as $data) {
            $thisref = &$refs[ $data['id'] ];
            $thisref['id'] = $data['id'];
            $thisref['parentid'] = $data['parent_id'];
            $thisref['name'] = $data['name_ru'];
            $model = ReportItems::find()->where(['=', 'category_id', $data['id']])->andWhere(['=', 'report_id', $this->id])->one();
            if($model) {
                $thisref['model'] = [
                    'budget_corrected' => $model->budget_corrected,
                    'budget_execution' => $model->budget_execution,
                    'budget_execution_fail' => ($model->budget_execution - $model->budget_corrected),
                    'budget_execution_percent' => $model->budget_execution_percent,
                    'budget_execution_percent_total' => $model->budget_execution_percent_total
                ];
            }
            if ($data['parent_id'] == NULL) {
                $list[ $data['id'] ] = &$thisref;
            } else if( isset($thisref['model']) && $thisref['model'] ){
                $refs[ $data['parent_id'] ]['children'][ $data['id'] ] = &$thisref;
            }
        }

        $this->data = json_encode($list);
        $this->save();
        return $list;
    }

    public function nodetree($param=array()) {
        $refs = array();
        $list = array();

        $nodes = Yii::$app->db->createCommand('select * from report_item_categories')->queryAll();

        foreach ($nodes as $data) {
            $thisref = &$refs[ $data['id'] ];
            $thisref['parentid'] = $data['parent_id'];
            $thisref['name'] = $data['name_ru'];
            $thisref['model'] = ReportItems::find()->where(['=', 'category_id', $data['id']])->andWhere(['=', 'report_id', $this->id])->all();
            if ($data['parent_id'] == NULL) {
                $list[ $data['id'] ] = &$thisref;
            } else if($thisref['model']){
                $refs[ $data['parent_id'] ]['children'][ $data['id'] ] = &$thisref;
            }
        }
        return $list;
    }

    public function nodetreeArr() {
        $refs = array();
        $list = array();

        $nodes = Yii::$app->db->createCommand('select * from report_item_categories')->queryAll();

        foreach ($nodes as $data) {
            $thisref = &$refs[ $data['id'] ];
            $thisref['parentid'] = $data['parent_id'];
            $thisref['name'] = $data['name_ru'];
            $thisref['model'] = ReportItems::find()->where(['=', 'category_id', $data['id']])->andWhere(['=', 'report_id', $this->id])->all();
            if ($data['parent_id'] == NULL) {
                $list[] = &$thisref;
            } else if($thisref['model']){
                $refs[ $data['parent_id'] ]['children'][  ] = &$thisref;
            }
        }
        return $list;
    }

    public function processExcel() {

        ExcellImport::prepareCategories();
        return ExcellImport::processFile($this);
    }

    public function beforeDelete() {
        if(parent::beforeDelete()) {
            $res = \yii\helpers\FileHelper::unlink( Yii::getAlias("@frontend") . '/web' . $this->filename );
            ReportItems::deleteAll(['report_id'=>$this->id]);
            return true;
        }
        return false;
    }

}

frontend/controllers/AnalyticsController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Reports;
use common\models\search\ReportsSearch;
use common\models\helpers\FilterIncome;
use common\models\helpers\FilterOutcome;
use common\models\helpers\FilterTransferts;
use common\models\ReportTypes;
use common\models\ReportItemCategories;
use common\models\Cities;

class AnalyticsController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionIncome() {

        // Ищем новейший отчет по Мангистауской области и проставляем данные в модель генерирующую графики
        $model = new FilterIncome();
        $city = Cities::findOne(['name_ru' => 'Мангистауская область']);
        // $report = Reports::find()->where(['city_id' => $city->id, 'type_id' => 2])->orderBy('date_fact DESC')->one();
        $model->city = $city->id;
        $model->year = date('Y');
        $model->month = date('m');
        $cities = \common\models\Cities::find()->select('name_ru')->indexBy('id')->column();
        return $this->render('income', [
            'model' => $model,
            'cities' => $cities,
            'years' => $model->getYears()
        ]);
    }

    public function actionIncomePie() {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        if(isset($_POST['FilterOutcome'])) {
            $model = new FilterOutcome();
            $model->load(Yii::$app->request->post());
        }
        else if(isset($_POST['FilterIncome'])) {
            $model = new FilterIncome();
            $model->load(Yii::$app->request->post());
        } else {
            $model = new FilterTransferts();
            $model->load(Yii::$app->request->post());
        }
        return $model->getPieChart();
    }

    public function actionOutcome() {
        // Ищем новейший отчет по Мангистауской области и проставляем данные в модель генерирующую графики
        $model = new FilterOutcome();
        $city = Cities::findOne(['name_ru' => 'Мангистауская область']);
        // $report = Reports::find()->where(['city_id' => $city->id, 'type_id' => 2])->orderBy('date_fact DESC')->one();
        $model->city = $city->id;
        $model->year = date('Y');
        $model->month = date('m');

        $cities = \common\models\Cities::find()->select('name_ru')->indexBy('id')->column();
        return $this->render('outcome', [
            'model' => $model,
            'cities' => $cities,
            'years' => $model->getYears()
        ]);
    }

    public function actionTransferts() {
        // Ищем новейший отчет по Мангистауской области и проставляем данные в модель генерирующую графики
        $model = new FilterTransferts();
        $city = Cities::findOne(['name_ru' => 'Мангистауская область']);
        $model->city = $city->id;
        $model->year = date('Y');
        $model->month = date('m');

        $cities = \common\models\Cities::find()->select('name_ru')->indexBy('id')->column();
        return $this->render('transferts', [
            'model' => $model,
            'cities' => $cities,
            'years' => $model->getYears()
        ]);
    }

    public function actionDynamicByMonth() {
        return $this->render('dynamic-by-month');
    }

    public function actionGovPrograms() {
        $model = Reports::find()->where('city_id = 2')->andWhere('type_id = 2')->orderBy('date_fact DESC')->one();
        return $this->render('gov-programs', ['model'=>$model]);
    }

    public function actionTest() {
        $model = Reports::find()->one();
        echo "<pre>"; print_r($model->shortTree()); echo "</pre>"; exit;
    }

    public function actionInvest() {
        $this->layout = "main_with_pic";
        return $this->render('invest');
    }

}

frontend/views/analytics/dynamic-by-month.php
<?php

    use yii\helpers\Html;
    $this->title = Yii::t('app', 'ПОМЕСЯЧНАЯ ДИНАМИКА ИСПОЛНЕНИЯ БЮДЖЕТА ПО ОТРАСЛЯМ');
    // $this->params['breadcrumbs'][] = $this->title;
?>

<div class="page glossary">


    <div class="heading"><?=$this->title?></div>

    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <label for="tt">Год: </label>
                <?=Html::dropDownList('tt', '', [2018, 2017, 2016], ['class' => 'form-control'])?>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="form-group">
                <label for="tt">Период:</label>
                <?=Html::dropDownList('tt', '', ['Январь - Декабрь'], ['class' => 'form-control'])?>
            </div>
        </div>
        <div class="col-sm-3 col-sm-offset-4">
            <div class="form-group">
                <label for="tt">Вид бюджета</label>
                <?=Html::dropDownList('tt', '', ['Местный', 'Республиканский','Местный/Республиканский'], ['class' => 'form-control'])?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-5">
            <div class="form-group">
                <label for="tt">Бюджет: </label>
                <?=Html::dropDownList('tt', '', ['Областной (включая районы и города) '], ['class' => 'form-control'])?>
            </div>
        </div>
        <div class="col-sm-3 col-sm-offset-4">
            <div class="form-group">
                <label for="tt"></label>
                <?=Html::dropDownList('tt', '', ['Тыс. тг.', 'Млн. тг.'], ['class' => 'form-control'])?>
            </div>
        </div>
    </div>

    <center>
        <img class="img img-responsive" src="/images/inc.jpg"/ style="max-width: 900px; padding: 40px 0;">
    </center>
    <center>
        <img class="img img-responsive" src="/images/inc2.jpg"/>
    </center>

</div>

frontend/views/analytics/dynamics-income.php
<?php

use yii\helpers\Html ;
use yii\widgets\ActiveForm ;
$this->title = Yii::t('app', 'Динамика поступлений в бюджет');
$this->registerJsFile('/js/Chart.bundle.min.js', ['depends' => frontend\assets\AppAsset::className()]);
$this->registerJsFile('/js/chartjs-plugin-datalabels.min.js', ['depends' => frontend\assets\AppAsset::className()]);
$this->registerJsFile('/js/charts/chart-dynamic-incomes.js', ['depends' => frontend\assets\AppAsset::className()]);
$this->registerJsFile('/js/treeview-income.js', ['depends' => frontend\assets\AppAsset::className()]);

$scr = <<< JS
    initTreeView({
        url: '/ajax/treeview-income'
    }, 'root');
    initTreeView({
        url: '/ajax/treeview-outcome'
    }, 'root2');


    $('#root2').hide();

    $(document).ready(function() {
        $('#report_id').change(function(e){
            var val = $(this).val();

            if(val == 1) {
                $('#root').show();
                $('#root2').hide();
            } else {
                $('#root2').show();
                $('#root').hide();
            }

            console.log($(this).val());
        });
    });


JS;

$this->registerJs(
$scr
);
?>

<div class="analytics">
    <div class="dynamics" style="min-height: 500px; width: 100%;">

        <?=Html::beginForm(['/ajax/dynamics-income'], 'post', ['class' => 'form-inline'])?>



            <div class="row" style="padding-bottom: 40px;">
                <div class="col-sm-9">

                    <div>
                        <div class="form-group">
                            <?=Html::dropDownList('report', 0, $reports, ['class'=>'form-control', 'id'=>'report_id'])?>
                        </div>

                        <div class="form-group">
                            <?=Html::dropDownList('city_id', 0, $cities, ['class'=>'form-control', 'id'=>'city_id'])?>
                        </div>

                        <!-- <div class="form-group">
                            <?=Html::dropDownList('type_id', 0, $types, ['class'=>'form-control', 'id'=>'type_id'])?>
                        </div> -->

                        <div class="form-group">
                            <?=Html::dropDownList('multiplier', 0, $multipliers, ['class'=>'form-control', 'id'=>'multiplier'])?>
                        </div>
                    </div>

                    <div>

                        <div class="form-group">
                            <?=Yii::t('app', 'Период: ')?>
                        </div>
                        <div class="form-group">
                            <?=Html::dropDownList('date_from', 0, $months, ['class'=>'form-control', 'id'=>'date_from'])?>
                        </div>
                        <div class="form-group">
                            <?=Yii::t('app', ' - ')?>
                        </div>
                        <div class="form-group">
                            <?=Html::dropDownList('date_to', 12, $months, ['class'=>'form-control', 'id'=>'date_to'])?>
                        </div>
                    </div>

                </div>
                <div class="col-sm-3">
                    <?=Html::button('Показать', ['class' => 'btn btn-success btn-block', 'id' => 'show'])?>
                </div>
            </div>
        <?=Html::endForm()?>

        <canvas id="dynamic-income"></canvas>
    </div>


    <div style="padding-top: 40px; padding-bottom: 90px; min-height: 400px;" id="root"></div>
    <div style="padding-top: 40px; padding-bottom: 90px; min-height: 400px;" id="root2"></div>

</div>

frontend/views/analytics/general.php
<?php
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    use kartik\date\DatePicker;
    use kartik\file\FileInput;

    $this->title = Yii::t('app', 'Основные показатели бюджета');
    $this->params['breadcrumbs'][] = $this->title;

?>


<h1><?=Yii::t('app', '')?></h1>

<div class="page analytics-general">


    <div class="heading center"><?=$this->title?></div>

    <!-- Поиск -->
    <div class="block-1">
        <?php $form = ActiveForm::begin(['options' => ['enctype'=>'multipart/form-data']]); ?>
        <div class="row">
            <div class="col-sm-3">

                <?=$form->field($model, 'date')->widget(DatePicker::className(), [
                    'options' => ['placeholder' => 'Укажите дату'],
                    'language' => 'ru',
                    'pluginOptions' => [
                        'autoclose'=>true,
                        'viewMode' => 'months',
                        'minViewMode' => 'months',
                    ]
                ])->label(false)?>

            </div>

            <div class="col-sm-3 col-sm-offset-1">
                <div class="form-field">
                    <?=$form->field($model, 'city_id')->dropDownList($cities)->label(false)?>
                </div>
            </div>

            <div class="col-sm-3">
                <div class="form-field">
                    <?=$form->field($model, 'type_id')->dropDownList($types)->label(false)?>
                </div>
            </div>

            <div class="col-sm-2">
                <?= Html::submitButton(Yii::t('app', 'Поиск'), ['class' => 'btn btn-success']) ?>
            </div>


        </div>
        <?php ActiveForm::end(); ?>

    </div>

    <?php if($model->id) : ?>

        <div class="row">
            <div class="col-sm-6">
                Установлено: <?=Yii::$app->formatter->asDecimal($model->incomes->budget_corrected)?><br />
                Исполнено: <?=Yii::$app->formatter->asDecimal($model->incomes->budget_execution)?><br />
                Исполнено % месяц: <?=$model->incomes->budget_execution_percent?> <br />
                Исполнено % год: <?=$model->incomes->budget_execution_percent_total?> <br />
            </div>
            <div class="col-sm-6">
                Установлено: <?=Yii::$app->formatter->asDecimal($model->outcomes->budget_corrected)?><br />
                Исполнено: <?=Yii::$app->formatter->asDecimal($model->outcomes->budget_execution)?><br />
                Исполнено % месяц: <?=$model->outcomes->budget_execution_percent?> <br />
                Исполнено % год: <?=$model->outcomes->budget_execution_percent_total?> <br />
            </div>
        </div>

    <?php else: ?>
        <div class="not-found"> Отчет не найден </div>
    <?php endif; ?>

</div>

frontend/views/analytics/gov-programs.php
<?php

    $this->title = "Государственные программы финансирования";

    $this->registerJsFile('/vendor/vis/vis.js', ['depends' => frontend\assets\AppAsset::className()]);
    $this->registerCssFile('/vendor/vis/vis-network.min.css');
    $__data = $model->shortTree();
    $data = json_encode($__data[2]);

        // echo "<pre>"; print_r( ($model->shortTree())[2]); echo "</pre>"; exit;
    $js = <<< JS
        var chart_data = $data;
JS;

    $this->registerJs($js, $this::POS_END);
    $this->registerJsFile('/js/charts/gov-programs.js', ['depends' => frontend\assets\AppAsset::className()]);
?>

<div class="gov-programs">

    <h3><?=$this->title?></h3>
    <h4 style="margin-bottom: 40px;"><?=Yii::t('app', 'По состоянию на {0}, Мангистауская область', [ Yii::$app->formatter->asDate($model->date, 'php:d.m.Y') ])?></h4>

        <div class="btn-group" role="group" aria-label="val">
          <button type="button" class="btn btn-default active"><?=Yii::t('app', 'тыс. тг')?></button>
          <button type="button" class="btn btn-default"><?=Yii::t('app', 'млн. тг')?></button>
        </div>

        <br />
        <br />

        <table class="table">
            <thead>
                <tr>
                    <th colspan="2">Наименование</th>
                    <th>Годовой план</th>
                    <th>План на отчетный период</th>
                    <th>Кассовое исполнение</th>
                    <th>%</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><img src="/images/style/circle-33.png" /></td>
                    <td> Государственная программа развития образования Республики Казахстан на 2011-2020 годы </td>
                    <td>21 520 709</td>
                    <td>6 301 693</td>
                    <td>5 807 227</td>
                    <td>92</td>
                </tr>
                <tr>
                    <td><img src="/images/style/circle-39.png" /></td>
                    <td>Государственная программа развития здравоохранения Республики Казахстан «Денсаулык» на 2016-2020 годы</td>
                    <td>4 037 385</td>
                    <td>1 772 819</td>
                    <td>1 654 945</td>
                    <td>93</td>
                </tr>
                <tr>
                    <td><img src="/images/style/circle-75.png" /></td>
                    <td>Программы по развитию агропромышленного комплекса в Республике Казахстан на 2013 – 2020 годы «Агробизнес – 2020»</td>
                    <td>1 062 557</td>
                    <td>177 077</td>
                    <td>177 074</td>
                    <td>100</td>
                </tr>
                <tr>
                    <td><img src="/images/style/circle-46.png" /></td>
                    <td>Программы развития продуктивной занятости и массового предпринимательства</td>
                    <td>1 585 632</td>
                    <td>398 084</td>
                    <td>383 047</td>
                    <td>96</td>
                </tr>
                <tr>
                    <td><img src="/images/style/circle-71.png" /></td>
                    <td>Дорожная карта бизнеса – 2020</td>
                    <td>1 055 765</td>
                    <td>1 005 765</td>
                    <td>1 005 765</td>
                    <td>100</td>
                </tr>
                <tr>
                    <td><img src="/images/style/circle-2.png" /></td>
                    <td>Программа развития регионов до 2020 года</td>
                    <td>24 116 088</td>
                    <td>5 108 801</td>
                    <td>5 186 718</td>
                    <td>102</td>
                </tr>
                <tr>
                    <td><img src="/images/style/circle-68.png" /></td>
                    <td>Программа развития и интеграции инфраструктуры транспортной системы РК до 2020 года</td>
                    <td>5 952 474</td>
                    <td>1 873 041</td>
                    <td>1 794 106</td>
                    <td>96</td>
                </tr>
                <tr>
                    <td><img src="/images/style/circle-23.png" /></td>
                    <td>Программа развития Мангистауской области на 2016-2020 годы</td>
                    <td>4 837 116</td>
                    <td>1 691 262</td>
                    <td>1 461 570</td>
                    <td>86</td>
                </tr>
            </tbody>
        </table>

    <div style="width: 100%; height: 500px; display: none;" id="mynetwork"></div>

</div>

frontend/views/analytics/gov-programs2.php
<?=Yii::t('app', 'По состоянию на {0}, Мангистауская область', [ Yii::$app->formatter->asDate($model->date, 'php:d.m.Y') ])?>

<?php
    $data = $model->shortTree();
    // echo "<pre>"; print_r($data); echo "</pre>"; exit;
    // echo "<pre>"; print_r($data[2]); echo "</pre>"; exit;
    // foreach ($data[2]['children'] as $key => $value) {
    //
    //     echo $value['name'] . " <br />";
    // }

?>

<div class="gov-programs">

<ul class="govprogram-tree">

<?php foreach ($data[2]['children'] as $item): ?>
    <li class="active">
        <img src="/images/style/test.png" />
        <?=$item['name'] . ". Назначено: " . round($item['model']['budget_corrected'] * 0.001, 1) . " млн. тг. / Исполнено: " . round($item['model']['budget_execution'] * 0.001) . " млн. тг." ?>
        <?php if($item['model']): ?>
            <!-- <ul> -->
                <table class="table">
                    <thead>
                        <tr>
                            <th>Наименование</th>
                            <th>Запланировано на конец года</th>
                            <th>Исполнено на текущий период</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($item['children'] as $item2): ?>
                            <!-- <li> -->
                                    <tr>
                                        <td><?=$item2['name']?></td>
                                        <td><?=round($item2['model']['budget_corrected'] * 0.001, 1)?></td>
                                        <td><?=round($item2['model']['budget_execution'] * 0.001)?></td>
                                    </tr>
                            <!-- </li> -->
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <!-- </ul> -->
        <?php endif; ?>
    </li>
<?php endforeach; ?>

</ul>

</div>

frontend/views/analytics/index.php
<?php
/* @var $this yii\web\View */
?>
<h1>analytics/index</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

frontend/views/analytics/transferts.php
<?php

use yii\helpers\Html ;
use yii\widgets\ActiveForm ;


$this->registerJsFile('/js/d3/d3.v4.min.js', ['depends' => frontend\assets\AppAsset::className()]);
$this->registerJsFile('/js/d3/d3.tip.js', ['depends' => frontend\assets\AppAsset::className()]);
// $this->registerJsFile('/js/Chart.bundle.min.js', ['depends' => frontend\assets\AppAsset::className()]);
// $this->registerJsFile('/js/chartjs-plugin-piechart-outlabels.js', ['depends' => frontend\assets\AppAsset::className()]);
// $this->registerJsFile('/js/chartjs-plugin-colorschemes.min.js', ['depends' => frontend\assets\AppAsset::className()]);
$this->registerJsFile('/js/analytics/income.js', ['depends' => frontend\assets\AppAsset::className()]);

?>

<div class="page-income block">

    <div class="block block-1">
        <div class="container">

            <h3><?=Yii::t('app', 'Межбюджетные трансферты')?></h3>

            <div class="text-block">
                <p><?=Yii::t('app', 'На странице приводятся показатели по межбюджетным трансфертам за текущий финансовый год и за плановый период. Динамика приводится в разрезе показателей по межбюджетным трансфертам. На круговой диаграмме доступен просмотр за текущий период. На гистограмме приводится сравнение показателей за два прошлых года и текущий финансовый год. В таблице более детализировано, представлены показатели за аналогичный гистограмме период.')?></p>
                <p><?=Yii::t('app', 'При наведении на элементы инфографики, в сплывающем «окне» отображается дополнительная информация по выбранному показателю.')?></p>
                <p><?=Yii::t('app', 'При клике на легенду к круговой диаграмме и гистограмме, выбранный показатель отключается на инфографике.')?></p>
                <p><?=Yii::t('app', 'При выборке периода, показатели в аналитическом отчете изменяются на принятые показатели с учетом уточнений данного периода.')?></p>
            </div>

            <h3><?=Yii::t('app', 'ПОКАЗАТЕЛИ МЕЖБЮДЖЕТНЫХ ТРАНСФЕРТОВ')?></h3>

            <?php $form = ActiveForm::begin([
                'id' => 'form-chart'
                ])?>

                <div class="row">
                    <div class="col-sm-3">
                        <?=$form->field($model, 'city')->dropDownList($cities)->label('Тип')?>
                    </div>
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-xs-6">
                                <?=$form->field($model, 'year')->dropDownList($years)->label('Период')?>
                            </div>
                            <div class="col-xs-6">
                                <?=$form->field($model, 'month')->dropDownList([
                                    '01' => 'Январь',
                                    '02' => 'Февраль',
                                    '03' => 'Март',
                                    '04' => 'Апрель',
                                    '05' => 'Май',
                                    '06' => 'Июнь',
                                    '07' => 'Июль',
                                    '08' => 'Август',
                                    '09' => 'Сентябрь',
                                    '10' => 'Октябрь',
                                    '11' => 'Ноябрь',
                                    '12' => 'Декабрь'
                                ])->label('&nbsp;')?>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <?=$form->field($model, 'coeficient')->dropDownList(['1' => 'тыс.тг', '0.001'  => 'млн.тг'])->label('&nbsp;')?>
                    </div>
                    <div class="col-sm-3">
                        <label class="control-label">&nbsp;</label> <br />
                        <button id="btn-chart" type="button" class="btn btn-success">Показать</button>
                    </div>
                </div>

            <?php ActiveForm::end()?>

            <div class="datetime"></div>
            <h3 class="center"><?=Yii::t('app', 'СТРУКТУРА МЕЖБЮДЖЕТНЫХ ТРАНСФЕРТОВ')?></h3>
            <div id="income-total" class="center"><?=Yii::t('app', 'Итого трансферты: {0}', [0])?></div>
            <div id="pie"></div>


            <h3 class="center"><?=Yii::t('app', 'ДИНАМИКА ПОКАЗАТЕЛЕЙ МЕЖБЮДЖЕТНЫХ ТРАНСФЕРТОВ')?></h3>
            <div id="stacked">
                <svg></svg>
            </div>

            <h3 class="center"><?=Yii::t('app', 'ДИНАМИКА ПОКАЗАТЕЛЕЙ МЕЖБЮДЖЕТНЫХ ТРАНСФЕРТОВ')?></h3>

            <?=Html::checkBoxList('tempo', '', [Yii::t('app', 'Темп роста к предыдущему году')])?>

            <table class="table table-bordered">
                <thead id="table-head">

                </thead>
                <tbody id="table">

                </tbody>
            </table>




        </div>
    </div>

</div>